In [30]:
import numpy as np 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten 

# 1. Prepare the data # Assume you have sequential data, e.g., time series data # Shape: (samples, timesteps, features) 

# For a univariate time series, 
features = 1 
data = np.array([ 
    [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 
    [15, 25, 35, 45, 55, 65, 75, 85, 95, 105], 
    [7, 17, 27, 37, 47, 57, 67, 77, 87, 97] ,
    [4, 14, 24, 34, 44, 54, 64, 74, 84, 94] ,
    [3, 8, 13, 18, 23, 28, 33, 38, 43, 48] ,
    [4, 9, 14, 19, 24, 29, 34, 39, 44, 49] ,
    [6, 10, 14, 18, 22, 26, 30, 34, 38, 42] ,
    [5, 7, 9, 11, 13, 15, 17, 19, 21, 23] 

    ]
    ) 

# For this example, let's create a simple target based on the last value # In a real scenario, this would be a separate target variable 
targets = np.array([110, 115, 107,104,53 ,54,46,25]) 
# Reshape data for Conv1D: (samples, timesteps, features) 
# If your data is (samples, timesteps), you need to add a feature dimension 

data = data.reshape((data.shape[0], data.shape[1], 1)) 
print(data.shape)
print(data)

n_steps = data.shape[1] # Number of timesteps 
n_features = data.shape[2] 
# Number of features # 2. Define the Conv1D-LSTM model 



(8, 10, 1)
[[[ 10]
  [ 20]
  [ 30]
  [ 40]
  [ 50]
  [ 60]
  [ 70]
  [ 80]
  [ 90]
  [100]]

 [[ 15]
  [ 25]
  [ 35]
  [ 45]
  [ 55]
  [ 65]
  [ 75]
  [ 85]
  [ 95]
  [105]]

 [[  7]
  [ 17]
  [ 27]
  [ 37]
  [ 47]
  [ 57]
  [ 67]
  [ 77]
  [ 87]
  [ 97]]

 [[  4]
  [ 14]
  [ 24]
  [ 34]
  [ 44]
  [ 54]
  [ 64]
  [ 74]
  [ 84]
  [ 94]]

 [[  3]
  [  8]
  [ 13]
  [ 18]
  [ 23]
  [ 28]
  [ 33]
  [ 38]
  [ 43]
  [ 48]]

 [[  4]
  [  9]
  [ 14]
  [ 19]
  [ 24]
  [ 29]
  [ 34]
  [ 39]
  [ 44]
  [ 49]]

 [[  6]
  [ 10]
  [ 14]
  [ 18]
  [ 22]
  [ 26]
  [ 30]
  [ 34]
  [ 38]
  [ 42]]

 [[  5]
  [  7]
  [  9]
  [ 11]
  [ 13]
  [ 15]
  [ 17]
  [ 19]
  [ 21]
  [ 23]]]


In [31]:
from tensorflow.keras.layers import Flatten


model = Sequential() 
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2)) 
model.add(Conv1D(filters=128, kernel_size=3, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2)) 
model.add(Flatten()) 
model.add(Dense(36)) 
model.add(Dense(1)) 
model.compile(optimizer='adam', loss='mse') 
model.fit(data, targets, epochs=200, verbose=0) 
# 5. Make a prediction 
# x_input = np.array([[3, 23, 33, 43, 53, 63, 73, 83, 93, 103]])
x_input = np.array([[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]])

x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 
print(f"Predicted value: {yhat}") 
model.summary()

Predicted value: [[33.210754]]


Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_12 (Conv1D)              │ (None, 8, 64)          │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_12 (MaxPooling1D) │ (None, 4, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_13 (Conv1D)              │ (None, 2, 128)         │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_13 (MaxPooling1D) │ (None, 1, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_9 (Flatten)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 36)             │         4,644 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            37 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,925 (347.37 KB)

 Trainable params: 29,641 (115.79 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 59,284 (231.58 KB)

In [32]:
for layer in model.layers:
    print(f"Layer: {layer.name}")
    print(layer.get_config())
    print("-"*50)


Layer: conv1d_12
{'name': 'conv1d_12', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'filters': 64, 'kernel_size': (3,), 'strides': (1,), 'padding': 'valid', 'data_format': 'channels_last', 'dilation_rate': (1,), 'groups': 1, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'module': 'keras.initializers', 'class_name': 'GlorotUniform', 'config': {'seed': None}, 'registered_name': None}, 'bias_initializer': {'module': 'keras.initializers', 'class_name': 'Zeros', 'config': {}, 'registered_name': None}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}
--------------------------------------------------
Layer: max_pooling1d_12
{'name': 'max_pooling1d_12', 'trainable': True, 'dtype': {'module': 'keras', 'class_name': 'DTypePolicy', 'config': {'name': 'float32'}, 'registered_name': None}, 'pool_size': (2,),

In [33]:
for layer in model.layers:
    weights = layer.get_weights()
    print(f"\nLayer: {layer.name}")
    for w in weights:
        print(w.shape)



Layer: conv1d_12
(3, 1, 64)
(64,)

Layer: max_pooling1d_12

Layer: conv1d_13
(3, 64, 128)
(128,)

Layer: max_pooling1d_13

Layer: flatten_9

Layer: dense_20
(128, 36)
(36,)

Layer: dense_21
(36, 1)
(1,)


In [41]:
conv_layer = model.layers[2]   # first layer
print(conv_layer.kernel_size)  # (3,)
print(conv_layer.filters)      # 64
print(conv_layer.input_shape)  # (None, 50, 10)
print(conv_layer.output_shape) # (None, 48, 64)


(3,)
128


AttributeError: 'Conv1D' object has no attribute 'input_shape'

In [36]:
for layer in model.layers:
    print(f"\nLayer: {layer.name}")
    print("Class:", layer.__class__.__name__)
    print("Input shape:", layer.input_shape)
    print("Output shape:", layer.output_shape)
    print("Config:", layer.get_config())
    print("Weights:", [w.shape for w in layer.get_weights()])



Layer: conv1d_12
Class: Conv1D


AttributeError: 'Conv1D' object has no attribute 'input_shape'

In [46]:
import numpy as np 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten 

# 1. Prepare the data # Assume you have sequential data, e.g., time series data # Shape: (samples, timesteps, features) 

# For a univariate time series, 
features = 1 
data = np.array([ 
    [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 
    [15, 25, 35, 45, 55, 65, 75, 85, 95, 105], 
    [7, 17, 27, 37, 47, 57, 67, 77, 87, 97] ,
    [4, 14, 24, 34, 44, 54, 64, 74, 84, 94] ,
    [3, 8, 13, 18, 23, 28, 33, 38, 43, 48] ,
    [4, 9, 14, 19, 24, 29, 34, 39, 44, 49] ,
    [6, 10, 14, 18, 22, 26, 30, 34, 38, 42] ,
    [5, 7, 9, 11, 13, 15, 17, 19, 21, 23] 

    ]
    ) 

# For this example, let's create a simple target based on the last value # In a real scenario, this would be a separate target variable 
targets = np.array([110, 115, 107,104,53 ,54,46,25]) 
# Reshape data for Conv1D: (samples, timesteps, features) 
# If your data is (samples, timesteps), you need to add a feature dimension 

data = data.reshape((data.shape[0], data.shape[1], 1)) 
print(data.shape)
print(data)

n_steps = data.shape[1] # Number of timesteps 
n_features = data.shape[2] 
# Number of features # 2. Define the Conv1D-LSTM model 



(8, 10, 1)
[[[ 10]
  [ 20]
  [ 30]
  [ 40]
  [ 50]
  [ 60]
  [ 70]
  [ 80]
  [ 90]
  [100]]

 [[ 15]
  [ 25]
  [ 35]
  [ 45]
  [ 55]
  [ 65]
  [ 75]
  [ 85]
  [ 95]
  [105]]

 [[  7]
  [ 17]
  [ 27]
  [ 37]
  [ 47]
  [ 57]
  [ 67]
  [ 77]
  [ 87]
  [ 97]]

 [[  4]
  [ 14]
  [ 24]
  [ 34]
  [ 44]
  [ 54]
  [ 64]
  [ 74]
  [ 84]
  [ 94]]

 [[  3]
  [  8]
  [ 13]
  [ 18]
  [ 23]
  [ 28]
  [ 33]
  [ 38]
  [ 43]
  [ 48]]

 [[  4]
  [  9]
  [ 14]
  [ 19]
  [ 24]
  [ 29]
  [ 34]
  [ 39]
  [ 44]
  [ 49]]

 [[  6]
  [ 10]
  [ 14]
  [ 18]
  [ 22]
  [ 26]
  [ 30]
  [ 34]
  [ 38]
  [ 42]]

 [[  5]
  [  7]
  [  9]
  [ 11]
  [ 13]
  [ 15]
  [ 17]
  [ 19]
  [ 21]
  [ 23]]]


In [55]:
model = Sequential() 
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2)) 
model.add(Conv1D(filters=128, kernel_size=3, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2)) 
model.add(Flatten()) 
model.add(Dense(32, activation='relu')) 
model.add(Dense(1)) # Output layer for regression (e.g., forecasting next value) 
# 3. Compile the model 
model.compile(optimizer='adam', loss='mse') 
# 4. Train the model (using dummy data for demonstration) 
model.fit(data, targets, epochs=200, verbose=0) 

# 5. Make a prediction 
# x_input = np.array([[70, 80, 90, 100, 110, 120, 130, 140, 150, 160]])
# x_input = np.array([[3, 23, 33, 43, 53, 63, 73, 83, 93, 103]])
# x_input = np.array([[13, 23, 33, 43, 53, 63, 73, 83, 93, 103]])
x_input = np.array([[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]])
x_input = x_input.reshape((1, n_steps, n_features)) 
yhat = model.predict(x_input, verbose=0) 
print(f"Predicted value: {yhat[0][0]:.2f}") 
 
 
 # Model summary 
 
model.summary()



Predicted value: 33.22


Model: "sequential_24"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_26 (Conv1D)              │ (None, 8, 64)          │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_26 (MaxPooling1D) │ (None, 4, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_27 (Conv1D)              │ (None, 2, 128)         │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_27 (MaxPooling1D) │ (None, 1, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_14 (Flatten)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_39 (Dense)                │ (None, 32)             │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_40 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 87,365 (341.27 KB)

 Trainable params: 29,121 (113.75 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 58,244 (227.52 KB)

In [6]:
model.predict(x_input, verbose=0) 

array([[204.43884]], dtype=float32)

In [12]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout

# Example data: 1000 samples, each with 50 timesteps, each timestep has 10 features
X = np.random.rand(1000, 50, 10)
y = np.random.randint(0, 2, 1000)  # binary labels

X[0]

array([[0.04025157, 0.57678429, 0.96430943, 0.02658589, 0.62500951,
        0.52027187, 0.09904338, 0.19698071, 0.17131208, 0.52974791],
       [0.03824005, 0.43802258, 0.8349718 , 0.99160106, 0.64665239,
        0.33047919, 0.61761129, 0.7756658 , 0.21200194, 0.63273228],
       [0.03115142, 0.89373759, 0.86621894, 0.68986271, 0.90540307,
        0.99133701, 0.18913432, 0.99770246, 0.62208801, 0.61936163],
       [0.54977749, 0.08178371, 0.62712848, 0.31785504, 0.5948566 ,
        0.75092346, 0.33894088, 0.5368729 , 0.18956027, 0.96304599],
       [0.69338749, 0.58926989, 0.46738024, 0.05099736, 0.32818094,
        0.22059768, 0.14887623, 0.02469024, 0.162307  , 0.02850199],
       [0.28392447, 0.5300743 , 0.61066034, 0.59017679, 0.89697764,
        0.72288774, 0.98224939, 0.28312391, 0.61516062, 0.51027445],
       [0.98429015, 0.74992661, 0.31497377, 0.23485637, 0.15171781,
        0.68799413, 0.49896737, 0.67676941, 0.34747899, 0.7559266 ],
       [0.55992515, 0.71848721, 0.9691694

In [ ]:
# Model
model = Sequential([
    Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(50, 10)),
    MaxPooling1D(pool_size=2),
    LSTM(100, return_sequences=False),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

# Training
history = model.fit(X, y, epochs=5, batch_size=32, validation_split=0.2)

In [56]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GlobalMaxPooling1D, Dense

# Example: 1000 samples, 50 timesteps, 10 features
X = np.random.randn(1000, 50, 10)
y = np.random.randint(0, 2, 1000)

model = Sequential([
    Conv1D(64, 3, activation='relu', input_shape=(50, 10)),
    MaxPooling1D(2),
    Conv1D(128, 3, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')  # binary classification
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


Model: "sequential_25"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_28 (Conv1D)              │ (None, 48, 64)         │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_28 (MaxPooling1D) │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_29 (Conv1D)              │ (None, 22, 128)        │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_max_pooling1d            │ (None, 128)            │             0 │
│ (GlobalMaxPooling1D)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,009 (136.75 KB)

 Trainable params: 35,009 (136.75 KB)

 Non-trainable params: 0 (0.00 B)