In [1]:
b = [1, 2, 3]


In [3]:
b.pop()


3

In [4]:
b

[1, 2]

In [5]:
def add_numbers(a, b):
    """
    Add two numbers together

    Returns
    -------
    the_sum : type of arguments
    """
    return a + b
    

In [6]:
add_numbers?

Signature: add_numbers(a, b)
Docstring:
Add two numbers together

Returns
-------
the_sum : type of arguments
File:      /tmp/ipykernel_15645/153281870.py
Type:      function

In [8]:
a = [1, 2, 3]

b = a

c = list(a)

In [9]:
a

[1, 2, 3]

In [10]:
c

[1, 2, 3]

In [13]:
 s = "12\3"

 print(s)

12


In [20]:
from  datetime import datetime,date,time
dt2 = datetime(2011, 11, 15, 22, 30)
dt = datetime(2011, 12, 15, 22, 30)
delta = dt2 - dt

In [21]:
delta

datetime.timedelta(days=-30)

In [22]:
('foo', 'bar') * 4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

In [24]:
[1, 2] * 4

[1, 2, 1, 2, 1, 2, 1, 2]

In [44]:
d =  {'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 5: 'some value'}

In [49]:
p = { key:d[key] for key in d }
p

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [27]:
d.keys()

dict_keys(['a', 'b', 7, 5])

In [37]:
!pip3 install numpy
import numpy as np
x = np.arange(0, 20, 1)
y = 1 + x*2
X = x.reshape(-1, 1)

In [38]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [40]:
X

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [41]:
x = np.arange(0,20,1)
X = np.c_[x, x**2, x**3]

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
X

array([[   0,    0,    0],
       [   1,    1,    1],
       [   2,    4,    8],
       [   3,    9,   27],
       [   4,   16,   64],
       [   5,   25,  125],
       [   6,   36,  216],
       [   7,   49,  343],
       [   8,   64,  512],
       [   9,   81,  729],
       [  10,  100, 1000],
       [  11,  121, 1331],
       [  12,  144, 1728],
       [  13,  169, 2197],
       [  14,  196, 2744],
       [  15,  225, 3375],
       [  16,  256, 4096],
       [  17,  289, 4913],
       [  18,  324, 5832],
       [  19,  361, 6859]])

In [50]:
w_in = np.zeros((1))

In [51]:
w_in

array([0.])